# Generated by Django 3.2.12 on 2022-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=255)),
                ("property_address_1", models.CharField(max_length=255)),
                ("property_address_2", models.CharField(max_length=255)),
                ("property_address_3", models.CharField(max_length=255)),
                ("property_address_4", models.CharField(max_length=255)),
                ("unit_name", models.CharField(max_length=60)),
                ("tenant_name", models.CharField(max_length=60)),
                ("lease_start_date", models.DateField()),
                ("lease_end_date", models.DateField()),
                ("lease_years", models.IntegerField()),
                ("current_rent", models.FloatField()),
            ],
        ),
    ]
