version: '3'

networks:
  default-network:
    driver: bridge

services:
  django:
      build: .
      command: "sh entry_point.sh"
      volumes:
        - .:/code
      ports:
        - "80:8000"
      container_name: django
      networks:
        - default-network
      restart: on-failure